/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 21 06:54:18 GMT 2020
 */

package org.apache.groovy.internal.util;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.groovy.internal.util.UnicodeConst;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UnicodeConst_ESTest extends UnicodeConst_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UnicodeConst unicodeConst0 = new UnicodeConst();
      assertEquals('\u0000', UnicodeConst.ZERO);
  }
}
