/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 21 06:51:11 GMT 2020
 */

package org.apache.groovy.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.groovy.util.Arrays;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Arrays_ESTest extends Arrays_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Object[][] objectArray0 = new Object[4][0];
      objectArray0[0] = (Object[]) null;
      // Undeclared exception!
      try { 
        Arrays.concat(objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.groovy.util.Arrays", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Object[][] objectArray0 = new Object[8][0];
      objectArray0[0] = (Object[]) stringArray0;
      Object[] objectArray1 = new Object[4];
      Object object0 = new Object();
      objectArray1[0] = object0;
      objectArray0[2] = objectArray1;
      // Undeclared exception!
      try { 
        Arrays.concat(objectArray0);
        fail("Expecting exception: ArrayStoreException");
      
      } catch(ArrayStoreException e) {
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Object[][] objectArray0 = new Object[24][5];
      objectArray0[18] = (Object[]) null;
      Object[] objectArray1 = Arrays.concat(objectArray0);
      assertNotNull(objectArray1);
      assertEquals(115, objectArray1.length);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String[][] stringArray0 = new String[0][6];
      String[] stringArray1 = Arrays.concat(stringArray0);
      assertNull(stringArray1);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Object[][] objectArray0 = new Object[4][0];
      Object[] objectArray1 = Arrays.concat(objectArray0);
      assertNotNull(objectArray1);
      assertEquals(0, objectArray1.length);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Integer[] integerArray0 = Arrays.concat((Integer[][]) null);
      assertNull(integerArray0);
  }
}
