/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 21 06:54:02 GMT 2020
 */

package org.apache.groovy.util;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.groovy.util.ObjectHolder;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ObjectHolder_ESTest extends ObjectHolder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ObjectHolder<Object> objectHolder0 = new ObjectHolder<Object>();
      Object object0 = objectHolder0.getObject();
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer integer0 = new Integer((-9));
      ObjectHolder<Object> objectHolder0 = new ObjectHolder<Object>(integer0);
      objectHolder0.setObject(integer0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Integer integer0 = new Integer((-9));
      ObjectHolder<Object> objectHolder0 = new ObjectHolder<Object>(integer0);
      Object object0 = objectHolder0.getObject();
      assertEquals((-9), object0);
  }
}
