/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 21 06:55:14 GMT 2020
 */

package org.apache.groovy.internal.metaclass;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.groovy.internal.metaclass.MetaClassConstant;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MetaClassConstant_ESTest extends MetaClassConstant_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MetaClassConstant<Object> metaClassConstant0 = null;
      try {
        metaClassConstant0 = new MetaClassConstant<Object>((Class<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }
}
