/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 21 06:54:32 GMT 2020
 */

package org.apache.groovy.internal.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.lang.invoke.SwitchPoint;
import org.apache.groovy.internal.util.Function;
import org.apache.groovy.internal.util.ReevaluatingReference;
import org.apache.groovy.internal.util.Supplier;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ReevaluatingReference_ESTest extends ReevaluatingReference_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Class<Object> class0 = Object.class;
      ReevaluatingReference<ReevaluatingReference<Object>> reevaluatingReference0 = null;
      try {
        reevaluatingReference0 = new ReevaluatingReference<ReevaluatingReference<Object>>(class0, (Supplier<ReevaluatingReference<Object>>) null, (Function<ReevaluatingReference<Object>, SwitchPoint>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.groovy.internal.util.ReevaluatingReference", e);
      }
  }
}
