/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 21 06:54:18 GMT 2020
 */

package org.apache.groovy.plugin;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.groovy.plugin.DefaultRunners;
import org.apache.groovy.plugin.GroovyRunner;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DefaultRunners_ESTest extends DefaultRunners_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GroovyRunner groovyRunner0 = DefaultRunners.junit3TestRunner();
      assertNotNull(groovyRunner0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GroovyRunner groovyRunner0 = DefaultRunners.junit3SuiteRunner();
      assertNotNull(groovyRunner0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GroovyRunner groovyRunner0 = DefaultRunners.junit4TestRunner();
      assertNotNull(groovyRunner0);
  }
}
