/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 21 06:12:25 GMT 2020
 */

package org.apache.groovy.metaclass;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.lang.reflect.Array;
import org.apache.groovy.internal.metaclass.MetaClassConstant;
import org.apache.groovy.internal.util.ReevaluatingReference;
import org.apache.groovy.metaclass.MetaClass;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MetaClass_ESTest extends MetaClass_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MetaClass<Integer> metaClass0 = new MetaClass<Integer>((ReevaluatingReference<MetaClassConstant<Integer>>) null);
      assertNotNull(metaClass0);
      
      Class<String>[] classArray0 = (Class<String>[]) Array.newInstance(Class.class, 9);
      // Undeclared exception!
      try { 
        metaClass0.getMethod("J`;vmFB$|qJYV=", classArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.groovy.metaclass.MetaClass", e);
      }
  }
}
