/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 21 06:24:32 GMT 2020
 */

package org.apache.groovy.metaclass;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.groovy.metaclass.Realm;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Realm_ESTest extends Realm_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        Realm.newRealm((String) null, (Realm) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // missing realm name
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Realm realm0 = Realm.newRealm("[OP lTCUv8[K)", (Realm) null);
      // Undeclared exception!
      try { 
        realm0.getMetaClass((Class<String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Realm realm0 = Realm.newRealm("", (Realm) null);
      Realm realm1 = Realm.newRealm("", realm0);
      assertNotSame(realm0, realm1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Realm realm0 = Realm.newRealm("", (Realm) null);
      String string0 = realm0.toString();
      assertEquals("Realm{name='', parent=Realm{name='ROOT', parent=null}}", string0);
  }
}
